- id: import-future-annotations
  name: add postponed evaluation of annotations import
  description: This hook checks presence of import `from __future__ import annotations` in python files and adds it if missing
  entry: import-future-annotations
  language: python
  types: [python]
